server:
  port: 40000
spring:
  datasource:
    url: jdbc:h2:mem:demo1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  logging.level:
    org.hibernate.SQL: debug # 쿼리 로그로 남기는것
  h2:
    console:
      path: /h2-console
      enabled: true